# Generated by Django 3.0 on 2019-12-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, default='', max_length=255)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('product_price', models.CharField(blank=True, default='', max_length=30)),
                ('product_desc', models.TextField(blank=True, default=None, max_length=2000)),
            ],
        ),
    ]
